"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# PyInstaller / desktop bundle: project data (templates, static, .env, db) lives next to the exe.
# Set by packaging/launcher.py before Django loads.
_bundle = os.getenv("MEGACNC_BUNDLE_ROOT")
if _bundle:
    BASE_DIR = Path(_bundle).resolve()
else:
    BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _discover_template_dirs():
    """
    Dev: BASE_DIR/templates.
    PyInstaller onedir: often under BASE_DIR/megacnc_dt_* or BASE_DIR/_internal/megacnc_dt_*.
    """
    names = ("megacnc_dt_templates", "templates")
    roots = [BASE_DIR]
    internal = BASE_DIR / "_internal"
    if internal.is_dir():
        roots.append(internal)
    out = []
    seen = set()
    for root in roots:
        for name in names:
            p = (root / name).resolve()
            if p.is_dir():
                key = str(p)
                if key not in seen:
                    seen.add(key)
                    out.append(p)
    return out if out else [BASE_DIR / "templates"]


def _discover_static_dirs():
    names = ("megacnc_dt_static", "static")
    roots = [BASE_DIR]
    internal = BASE_DIR / "_internal"
    if internal.is_dir():
        roots.append(internal)
    out = []
    seen = set()
    for root in roots:
        for name in names:
            p = (root / name).resolve()
            if p.is_dir():
                key = str(p)
                if key not in seen:
                    seen.add(key)
                    out.append(str(p))
    return tuple(out) if out else (str(BASE_DIR / "static"),)


# Optional: separate writable dir for SQLite (e.g. onefile or portable USB)
_data = os.getenv("MEGACNC_DATA_DIR")
if _data:
    _data_path = Path(_data).resolve()
    _data_path.mkdir(parents=True, exist_ok=True)

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dp#h4@*pio(2yfpeuu-f7va!^92c#fy&wif+goo&^g(bzy5d9b')

DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django_celery_beat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'megacellcnc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': _discover_template_dirs(),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'custom_context_processor.dz_static',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database — set DB_ENGINE=sqlite3 in .env to use SQLite (no PostgreSQL needed)
DB_ENGINE = os.getenv('DB_ENGINE', 'postgresql')

if DB_ENGINE == 'sqlite3':
    _sqlite_name = (
        Path(_data).resolve() / "db.sqlite3"
        if _data
        else BASE_DIR / "db.sqlite3"
    )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_name,
            # Waitress + background poller thread (desktop bundle) need multi-threaded SQLite access
            'OPTIONS': {
                'timeout': 25,
                'check_same_thread': False,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'mcccnc'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'MccAdmin'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Celery Configuration
# Set CELERY_EAGER=True in .env to run tasks synchronously (no Redis/Celery needed)
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_EAGER', 'False').lower() in ('true', '1', 'yes')
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_IMPORTS = ('megacellcnc.tasks',)
DJANGO_CELERY_BEAT_TZ_AWARE=False
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-devices-status-5s': {
        'task': 'megacellcnc.tasks.check_all_devices',
        'schedule': 5.0,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

if DEBUG:
    STATICFILES_DIRS = _discover_static_dirs()
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
