services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mcccnc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MccAdmin
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    image: ghcr.io/heinz-leiser-ai/megacnc:latest
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
    network_mode: host
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:MccAdmin@localhost:5432/mcccnc
      - REDIS_URL=redis://localhost:6379/0
    cap_add:
      - NET_ADMIN

  celeryworker:
    build: .
    command: celery -A dashboard worker --loglevel=info
    network_mode: host
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:MccAdmin@localhost:5432/mcccnc
      - REDIS_URL=redis://localhost:6379/0

  celerybeat:
    build: .
    command: celery -A dashboard beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    network_mode: host
    volumes:
      - .:/app
      - /home/heinz/Dokumente/megacell/test:/data
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:MccAdmin@localhost:5432/mcccnc
      - REDIS_URL=redis://localhost:6379/0

volumes:
  postgres_data:

