# Generated by Django 5.0.2 on 2024-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0002_alter_projects_devcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
