# Generated by Django 5.0.2 on 2024-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0003_slot_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='removal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
