# Generated by Django 5.0.2 on 2024-02-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0004_alter_cells_removal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='active_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_slots', to='megacellcnc.cells'),
        ),
    ]
