# Generated by Django 5.0.2 on 2024-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0005_slot_active_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='discharge_mode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
