# Generated by Django 5.0.2 on 2024-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0006_device_discharge_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='discharge_current',
            field=models.IntegerField(default=0),
        ),
    ]
