# Generated by Django 5.0.2 on 2024-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0007_device_discharge_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cell_per_group',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='cell_to_group',
            field=models.IntegerField(default=16),
        ),
    ]
