# Generated by Django 5.0.2 on 2024-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0008_device_cell_per_group_device_cell_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltestdata',
            name='charging_capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
