# Generated by Django 4.2.10 on 2024-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0010_printersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersettings',
            name='IsDualLabel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printersettings',
            name='LabelHeight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='printersettings',
            name='LabelRotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printersettings',
            name='LabelWidth',
            field=models.FloatField(default=0),
        ),
    ]
