# Generated by Django 4.2.10 on 2024-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0011_alter_printersettings_isduallabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersettings',
            name='PrinterHost',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='printersettings',
            name='PrinterName',
            field=models.CharField(default='', max_length=150),
        ),
    ]
