# Generated by Django 4.2.10 on 2024-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0013_printersettings_customfield1'),
    ]

    operations = [
        migrations.AddField(
            model_name='printersettings',
            name='LabelShape',
            field=models.CharField(default='square', max_length=150),
        ),
    ]
