# Generated by Django 4.2.10 on 2024-04-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0014_printersettings_labelshape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='megacellcnc.projects'),
        ),
    ]
