# Generated by Django 4.2.10 on 2024-04-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0015_alter_cells_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megacellcnc.projects'),
        ),
    ]
