# Generated by Django 4.2.10 on 2024-05-02 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0017_alter_cells_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batteries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('UUID', models.CharField(max_length=150)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('parallel', models.IntegerField(blank=True, null=True)),
                ('cell_type', models.CharField(max_length=150)),
                ('voltage', models.FloatField()),
                ('capacity', models.FloatField()),
                ('status', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('available', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cells',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_cells', to='megacellcnc.batteries'),
        ),
    ]
