# Generated by Django 4.2.10 on 2024-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0019_cells_bat_id_cells_bat_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='bat_position',
            field=models.CharField(default='', max_length=150),
        ),
    ]
