# Generated by Django 5.0.2 on 2026-02-08 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0021_remove_cells_bat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellReplacementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cell_uuid', models.CharField(max_length=150)),
                ('new_cell_uuid', models.CharField(max_length=150)),
                ('slot_series', models.IntegerField()),
                ('slot_parallel', models.IntegerField()),
                ('old_capacity', models.FloatField()),
                ('new_capacity', models.FloatField()),
                ('old_esr', models.FloatField(blank=True, null=True)),
                ('new_esr', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(default='defective', max_length=255)),
                ('replaced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('replaced_by', models.CharField(default='system', max_length=150)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_logs', to='megacellcnc.batteries')),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
    ]
