# Generated by Django 5.0.2 on 2026-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacellcnc', '0022_cellreplacementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cells',
            name='condition',
            field=models.CharField(choices=[('good', 'Gut'), ('defective', 'Defekt'), ('reserved', 'Reserviert'), ('unknown', 'Unbekannt')], default='good', max_length=50),
        ),
    ]
